name: PR prsk cheering

on:
  pull_request:
    types: [opened]

jobs:
  set-prsk-label-and-comments:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set prsk label and comments
        uses: narumikr/link-sekai-actions/prsk-cheering@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}